### ISSUE TITLE
Fintium website content design

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-design2#18]
**Description**
Fintium website content design.

**Reference**
- universelabs/universe-design2#17 Fintium FinTech Challenge one page website design

**Tasks**
- [x] Navbar section design.
- [x] Hero section design.
- [x] About or event description section design.
- [x] Schedule section design.
- [x] Speaker section design.
- [x] Sponsor section design.
- [x] Registration page design.
- [x] Contact page design.
- [x] Footer section design.
- [x] universelabs/universe-design2#32 Fintium Eventbrite page design.

**Comment by guylepage3** [comment]
Working on this now.

**Comment by guylepage3** [comment]
https://github.com/universelabs/universe-design2/issues/17

**Comment by guylepage3** [comment]
[fintium-sell-sheet.pdf](https://github.com/universelabs/universe-design/files/3307260/fintium-sell-sheet.pdf)

**Comment by guylepage3** [comment]
Done
