### ISSUE TITLE
Print production for Universe Feather device packaging

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-design2#23]
**Description**
Print production for Universe Feather device packaging.

**Tasks**
- [x] ~~Acquire printer specs.~~
- [x] ~~Build out document~~
- [x] ~~Build registration~~
- [x] ~~Build out dielines.~~
- [x] ~~Print production for Universe Feather device packaging.~~
- [x] ~~Check all dielines.~~
- [x] ~~Check color for anything other than CMYK.~~
- [x] ~~Export PDF for printer check.~~
- [x] ~~Get verification from printer.~~
- [x] ~~Preflight and package for printer.~~

**Comment by guylepage3** [comment]
No longer designing packaging for this release. Just the card.
