### ISSUE TITLE
Print production for Universe Feather instruction card

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-design2#25]
**Description**
Print production for Universe Feather instruction card.

**Tasks**
- [ ] Acquire printer specs.
- [ ] Build out document
- [ ] Build registration
- [ ] Build out dielines.
- [ ] Print production for Universe Feather device packaging.
- [ ] Check all dielines.
- [ ] Check color for anything other than CMYK.
- [ ] Export PDF for printer check.
- [ ] Get verification from printer.
- [ ] Preflight and package for printer.

**Comment by guylepage3** [comment]
Closing issue.
