### ISSUE TITLE
Design new architecture illustration

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-design2#30]
**Description**
Now that we have our first v1 Universe Architecture a new illustration needs to be designed for applying to various communications.

**Tasks**
- [x] Define style.
- [x] Design illustration.

**References**
- [universe-universe#34 Universe architecture v1](https://github.com/universelabs/universe/issues/34)

**Comment by guylepage3** [comment]
<img width="450" alt="2019-08-09-universe-software-architecture" src="https://user-images.githubusercontent.com/1711854/62784434-786b5a80-ba8c-11e9-8d93-99dbb94bdf11.jpg">
<img width="450" alt="IMG_20190810_152030" src="https://user-images.githubusercontent.com/1711854/62965984-16845b00-bdd4-11e9-9942-74ea8c00d562.jpg">
<img width="450" alt="IMG_20190810_152030" src="https://user-images.githubusercontent.com/1711854/62965985-16845b00-bdd4-11e9-82f2-a619837c456a.jpg">

**Comment by guylepage3** [comment]
<img width="1495" alt="Screen Shot 2019-08-13 at 8 40 26 PM" src="https://user-images.githubusercontent.com/1711854/62986656-9decc100-be0a-11e9-8b87-2d3045b1b65b.png">

**Comment by guylepage3** [comment]
Done

**Comment by guylepage3** [comment]
Adding last night's Slack comments about the diagram.

@guylepage3 8:53 PM
New Universe Architecture Diagram

@itamarreif 8:56 PM
just one note, i'd put the bluetooth logo on the feather rather than in the middle, as bluetooth is just one implementation of the api (i.e. apple enclave being a stand-in for bluetooth)

@guylepage3 8:57 PM
Hm. Would the iPhone use Bluetooth to connect though?
cc @itamarreif 

@itamarreif 9:03 PM
no, core would be running on the device

**Comment by guylepage3** [comment]
Updating this now.

**Comment by guylepage3** [comment]
- [x] Update core icon
- [x] Remove Bluetooth icon
- [x] Tighten up diagram

**Comment by guylepage3** [comment]
<img width="1492" alt="Screenshot 2019-08-14 12 05 16" src="https://user-images.githubusercontent.com/1711854/63037006-23fd1c00-be8c-11e9-9c96-c6b8880b0063.png">

**Comment by guylepage3** [comment]
@itamarreif Can you take a look at the updated version? Thank you sir.

**Comment by guylepage3** [comment]
<img width="1496" alt="Screenshot 2019-08-14 17 52 44" src="https://user-images.githubusercontent.com/1711854/63059060-60487080-bebc-11e9-95cc-a935d3d740da.png">
